export const sample_foods = [
    {
        id: '1',
        name: 'Ube Cake',
        cookTime: '30',
        price: 10,
        favourite: true,
        ingredients: ['Purple Yam', 'Coconut Sport' ],
        stars: 4.5,
        imageUrl: 'food-1.jpg',
        tags: ['Cakes', 'Dessert', 'Cold Food'],
    },
    {
        id: '2',
        name: 'Sansrival',
        cookTime: '30',
        price: 7,
        favourite: false,
        ingredients: ['Cashew Nuts', 'Buttercream Filling' ],
        stars: 3.5,
        imageUrl: 'food-2.jpg',
        tags: ['Cakes', 'Dessert', 'Cold Food'],

    },
    {
        id: '3',
        name: 'Black Forest',
        cookTime: '30',
        price: 3,
        favourite: false,
        ingredients: ['Cherry Filling', 'Kirsch (Cherry Brandy', 'Chocolate Cake Layers'],
        stars: 2,
        imageUrl: 'food-3.jpg',
        tags: ['Cakes', 'Dessert', 'Cold Food'],
    },
    {
        id: '4',
        name: 'Pandesal',
        cookTime: '120',
        price: 5,
        favourite: false,
        ingredients: ['Yeast', 'Sugar', 'Bread Crumbs'],
        stars: 3,
        imageUrl: 'food-4.jpg',
        tags: ['Bread'],
    },
    {
        id: '5',
        name: 'Ensaymada',
        cookTime: '120',
        price: 7.5,
        favourite: false,
        ingredients: ['Butter', 'Cheese', 'Egg Yolk'],
        stars: 4.5,
        imageUrl: 'food-5.jpg',
        tags: ['Bread'],
    },
    {
        id: '6',
        name: 'Red Velvet Cupcake',
        cookTime: '15',
        price: 7.5,
        favourite: false,
        ingredients: ['Cocoa Powder', 'Buttermilk', 'Cream Cheese Frosting'],
        stars: 4.5,
        imageUrl: 'food-6.jpg',
        tags: ['Cupcakes', 'Dessert', 'Cold Food'],
    },
    {
        id: '7',
        name: 'Peanut Butter Cupcakes',
        cookTime: '15',
        price: 10,
        favourite: true,
        ingredients: ['Peanut Butter', 'Vanilla Extract'],
        stars: 4.5,
        imageUrl: 'food-1.jpg',
        tags: ['Cupcakes', 'Dessert', 'Cold Food'],
    },
    {
        id: '8',
        name: 'Strawberry Cupcake',
        cookTime: '15',
        price: 7,
        favourite: false,
        ingredients: ['Strawberries', 'Vanilla Extract'],
        stars: 3.5,
        imageUrl: 'food-2.jpg',
        tags: ['Cupcakes', 'Dessert', 'Cold Food'],

    },
    {
        id: '9',
        name: 'Halo Halo',
        cookTime: '5',
        price: 3,
        favourite: false,
        ingredients: ['Leche Flan', 'Ube Halaya', 'Sweetened Fruits'],
        stars: 2,
        imageUrl: 'food-3.jpg',
        tags: ['Dessert', 'Cold Food'],
    },
    {
        id: '10',
        name: 'Biko (Sticky Rice)',
        cookTime: '3',
        price: 5,
        favourite: false,
        ingredients: ['Glutinous Rice', 'Coconut Milk & Cream', 'Brown Sugar'],
        stars: 3,
        imageUrl: 'food-4.jpg',
        tags: ['Dessert', 'Cold Food'],
    },
    {
        id: '11',
        name: 'Leche Flan (Caramel Pudding)',
        cookTime: '7',
        price: 5,
        favourite: false,
        ingredients: ['Evaporated Milk', 'Condensed Milk', 'Vanilla Extract'],
        stars: 4.5,
        imageUrl: 'food-5.jpg',
        tags: ['Dessert', 'Cold Food'],
    },
    {
        id: '12',
        name: 'Adobo',
        cookTime: '120',
        price: 30,
        favourite: false,
        ingredients: ['Chicken or Pork', 'Soy Sauce', 'Vinegar'],
        stars: 4.5,
        imageUrl: 'food-6.jpg',
        tags: ['Lunch', 'Hot Food'],
    },
    {
        id: '13',
        name: 'Lechon',
        cookTime: '150',
        price: 120,
        favourite: false,
        ingredients: ['Whole Roasted Pig'],
        stars: 4.5,
        imageUrl: 'food-6.jpg',
        tags: ['Lunch', 'Hot Food'],
    },
    {
        id: '14',
        name: 'Sinigang',
        cookTime: '20',
        price: 25,
        favourite: false,
        ingredients: ['Pork and Beef', 'Tamarind Soup', 'Fish Sauce'],
        stars: 4.5,
        imageUrl: 'food-6.jpg',
        tags: ['Lunch', 'Hot Food'],
    }
];

export const sample_tags = [
    {name: 'All'},
    {name: 'Cakes'},
    {name: 'Cupcakes'},
    {name: 'Bread'},
    {name: 'Dessert'},
    {name: 'Cold Food'},
    {name: 'Lunch'},
    {name: 'Hot Food'},
];

export const sample_user = [
    {
        id: 1, 
        name: 'Laurence Rico',
        email: 'admin@gmail.com',
        password: '123',
        address: 'Deanside',
        isAdmin: true,
    },
    {
        id: 2,
        name: 'Wolf Blitzer',
        email: 'Blitzer@gmail.com',
        password: '123',
        address: 'Braybrook',
        isAdmin: false,

    },
];